npm install --save-dev gulp
npm install --save-dev gulp-ruby-sass
npm install --save-dev gulp-plumber
npm install --save-dev gulp-livereload
npm install --save-dev gulp-uglify
npm install --save-dev gulp-concat
npm install --save-dev gulp-autoprefixer
npm install --save-dev gulp-minify-css
npm install --save-dev gulp-rename
npm install --save-dev gulp-notify
npm install --save-dev gulp-imagemin
npm install --save-dev imagemin-pngcrush